version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysqlHost
    environment:
      - MYSQL_DATABASE=devopsexam
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=dbadmin
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3306:3306
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker

  php:
    depends_on:
      - db
    build: .
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
      
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker

networks:
  lamp-docker:
    driver: bridge
